name: KitUI
author: Infernus101
api: [4.0.0, 3.0.0, 3.0.0-ALPHA3, 3.0.0-ALPHA4, 3.0.0-ALPHA5, 3.0.0-ALPHA6, 3.0.0-ALPHA12, 3.0.0-ALPHA11, 3.0.0-ALPHA13]
main: Infernus101\KitUI\Main
version: 1.0.0
permission: # kit permissions - kit.<kit name>
 kit.command:
  description: kit command!
  default: true
commands:
  kit:
    description: Kit UI!
